### PR TITLE
Update the tool

### PR DESCRIPTION
**Pull request by szymex73**
Hi, this PR serves two purposes:
1. It incorporates the custom kbkdf function into the project itself making so it doesn't require installation of a separate custom cryptography lib version that is out of date and could cause conflicts with other tools in the system 
2. Update the dependencies to match 1.

### CODE REVIEW

**Comment by dmb2168** [comment]
Hi @szymex73

**Comment by dmb2168** [comment]
hi @szymex73 - if you could sign our CLA at https://cla.developers.google.com/clas I'd love to merge your PR !

**Comment by szymex73** [comment]
Hey, I've agreed to the CLA

**Comment by dmb2168** [comment]
thank you!

**Pull request merged**
